src/main/java/com/realdolmen/thomasmore/domain/Winkelmand.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;

@Entity
public class Winkelmand implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne
    private User user;
    private GregorianCalendar datum;
    @ManyToOne
    private Betaalwijze betaalwijze;
    private Boolean isBesteld;
    @OneToMany(mappedBy = "winkelmand", cascade = {CascadeType.REMOVE}, fetch = FetchType.EAGER) //fetch.lazy geeft error
    private List<Item> items = new ArrayList<Item>();

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public GregorianCalendar getDatum() {
        return datum;
    }

    public void setDatum(GregorianCalendar datum) {
        this.datum = datum;
    }

    public Betaalwijze getBetaalwijze() {
        return betaalwijze;
    }

    public void setBetaalwijze(Betaalwijze betaalwijze) {
        this.betaalwijze = betaalwijze;
    }

    public Boolean getBesteld() {
        return isBesteld;
    }

    public void setBesteld(Boolean besteld) {
        isBesteld = besteld;
    }

    public List<Item> getItems() {
        return items;
    }

    public void setItems(List<Item> items) {
        this.items = items;
    }

    public void addItem(Item item) {
        items.add(item);
    }

    public double getTotalePrijs() {
        double prijs = 0;
        for(Item i : getItems()) {
            prijs += (i.getBoek().getPrijs() * (double) i.getAantal());
        }
        return prijs;
    }
}

src/main/java/com/realdolmen/thomasmore/controller/WinkelmandController.java
package com.realdolmen.thomasmore.controller;

import com.realdolmen.thomasmore.authentication.UserSession;
import com.realdolmen.thomasmore.domain.*;
//import com.realdolmen.thomasmore.service.ItemService;
import com.realdolmen.thomasmore.service.UserService;
import com.realdolmen.thomasmore.service.WinkelmandService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.util.List;

@ManagedBean
@SessionScoped
public class WinkelmandController {

    @ManagedProperty("#{winkelmandService}")
    private WinkelmandService winkelmandService;
    
    @ManagedProperty("#{userSession}")
    private UserSession userSession;

    //@ManagedProperty("#{itemService}")
    //private ItemService itemService;

    private User user; //voor te weten van wie de mand is

    private Item nieuwItem;

    private Winkelmand huidigeWinkelmand;

    public WinkelmandService getWinkelmandService() {
        return winkelmandService;
    }

    public void setWinkelmandService(WinkelmandService winkelmandService) {
        this.winkelmandService = winkelmandService;
    }

    public void setUserSession(UserSession userSession) {
        this.userSession = userSession;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Item getNieuwItem() {
        if(nieuwItem == null) {
            nieuwItem = new Item();
            nieuwItem.setAantal(1);
        }
        return nieuwItem;
    }

    public void setNieuwItem(Item nieuwItem) {
        this.nieuwItem = nieuwItem;
    }

    public List<Winkelmand> getBestellingen() {
        return winkelmandService.getBestellingen();
    }

    public Winkelmand getHuidigeWinkelmand() {
        if(huidigeWinkelmand == null) {
            return winkelmandService.getHuidigeWinkelmand(getUser());
        } else {
            return huidigeWinkelmand;
        }
    }

    public void setHuidigeWinkelmand(Winkelmand huidigeWinkelmand) {
        this.huidigeWinkelmand = huidigeWinkelmand;
    }

    public void saveHuidigeWinkelmand(){
        winkelmandService.save(getHuidigeWinkelmand());
    }

    private void bestel() {
        Winkelmand winkelmand = winkelmandService.getHuidigeWinkelmand(getUser());
        winkelmand.setBesteld(true);
        winkelmandService.save(winkelmand);
    }

    private void delete(){
        if (huidigeWinkelmand != null) {
            winkelmandService.delete(huidigeWinkelmand);
        }
    }

    public void addItem(Boek b) {
        if(huidigeWinkelmand == null) {
            huidigeWinkelmand = new Winkelmand();
            System.out.println("usersession is " + userSession);
            if (userSession != null && userSession.getUser() != null) {
                huidigeWinkelmand.setUser(userSession.getUser());
            }
            huidigeWinkelmand.setBesteld(false);
            winkelmandService.save(huidigeWinkelmand);
        }
        nieuwItem.setBoek(b);
        huidigeWinkelmand.addItem(nieuwItem);
        winkelmandService.save(huidigeWinkelmand);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Boek \"" + b.getTitel() + "\" toegevoegd."));
        nieuwItem = new Item(); //item resetten.
        nieuwItem.setAantal(1);
        winkelmandService.save(huidigeWinkelmand);
    }

    public String getAantalInMandNav() {
        if(huidigeWinkelmand == null || huidigeWinkelmand.getItems().size() == 0) {
            return "";
        } else {
            return "(" + huidigeWinkelmand.getItems().size() + ")";
        }
    }
}

src/main/webapp/bestelling/winkelmand.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>Winklemand</title>
    <link rel="stylesheet" type="text/css" href="../css/main.css"/>
</h:head>
<h:body>
    <ui:composition template="../template/template.xhtml">
        <ui:define name="content_titel">
            <h1>Winkelmand van #{winkelmandController.huidigeWinkelmand.user.voornaam}</h1>
        </ui:define>
        <ui:define name="content">
            <p:dataTable var="item" value="#{winkelmandController.getHuidigeWinkelmand().getItems()}">
                <p:column headerText="titel">
                    <h:outputText value="#{item.getBoek().getTitel()}"/>
                </p:column>
                <p:column headerText="auteur">
                    <h:outputText value="#{item.getBoek().getAuteur().getNaam()}"/>
                </p:column>
                <p:column headerText="prijs per stuk" >
                    <h:outputText value="€ #{item.getBoek().getPrijs()}"/>
                </p:column>
                <p:column headerText="aantal" >
                    <h:outputText value="#{item.getAantal()}"/>
                </p:column>
                <p:column  headerText="prijs">
                    <h:outputText value="€ #{item.getBoek().getPrijs() * item.getAantal()}"/>
                </p:column>
                <p:columnGroup type="footer">
                    <p:row>
                        <p:column colspan="3"/>
                        <p:column footerText="totale prijs: "/>
                        <p:column footerText="€ #{winkelmandController.huidigeWinkelmand.totalePrijs}"/>
                    </p:row>
                </p:columnGroup>
            </p:dataTable>
            <p class="btn btn-primary">bestel</p><!--TODO-->
        </ui:define>
    </ui:composition>
</h:body>
</html>