src/main/java/com/realdolmen/thomasmore/domain/Boek.java
package com.realdolmen.thomasmore.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Entity
public class Boek implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne
    private Genre genre;
    @ManyToOne
    private Auteur auteur;
    @ManyToOne
    private Uitgeverij uitgeverij;
    @OneToMany(mappedBy = "boek")
    private List<Item> items = new ArrayList<Item>();

    private String titel;
    private String beschrijving;
    private double prijs;
    private int voorraad;

    /** GETTERS & SETTERS */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Genre getGenre() {
        return genre;
    }

    public void setGenre(Genre genre) {
        this.genre = genre;
    }

    public Auteur getAuteur() {
        return auteur;
    }

    public void setAuteur(Auteur auteur) {
        this.auteur = auteur;
    }

    public Uitgeverij getUitgeverij() {
        return uitgeverij;
    }

    public void setUitgeverij(Uitgeverij uitgeverij) {
        this.uitgeverij = uitgeverij;
    }

    public List<Item> getItems() { return items; }

    public void setItems(List<Item> items) { this.items = items; }

    public String getTitel() {
        return titel;
    }

    public void setTitel(String titel) {
        this.titel = titel;
    }

    public String getBeschrijving() {
        return beschrijving;
    }

    public void setBeschrijving(String beschrijving) {
        this.beschrijving = beschrijving;
    }

    public double getPrijs() {
        return prijs;
    }

    public void setPrijs(double prijs) { this.prijs = prijs; }

    public int getVoorraad() {
        return voorraad;
    }

    public void setVoorraad(int voorraad) {
        this.voorraad = voorraad;
    }

}

src/main/java/com/realdolmen/thomasmore/controller/BoekController.java
package com.realdolmen.thomasmore.controller;

import com.realdolmen.thomasmore.domain.Auteur;
import com.realdolmen.thomasmore.domain.Boek;
import com.realdolmen.thomasmore.domain.Genre;
import com.realdolmen.thomasmore.domain.Uitgeverij;
import com.realdolmen.thomasmore.service.AuteurService;
import com.realdolmen.thomasmore.service.BoekService;
import com.realdolmen.thomasmore.service.GenreService;
import com.realdolmen.thomasmore.service.UitgeverijService;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.text.Collator;
import java.util.*;

@ManagedBean
@SessionScoped
public class BoekController {

    //Autowired kunnen we niet gebruiken in JSF, daarom gebruiken we hier dit om een spring bean te injecteren.
    @ManagedProperty("#{boekService}")
    private BoekService boekService;
    @ManagedProperty("#{genreService}")
    private GenreService genreService;
    @ManagedProperty("#{auteurService}")
    private AuteurService auteurService;
    @ManagedProperty("#{uitgeverijService}")
    private UitgeverijService uitgeverijService;
    private Boek boek;

    private List<Boek> boeken;
    public List<Boek> getBoeken() {
        if (boeken == null) {
            boeken = boekService.findAllBoeken();
        }
//        sorteerBoeken();
        return boeken;
    }

    private String newBoekTitel;
    private String newBoekBeschrijving;
    private double newBoekPrijs;
    private Genre newBoekGenre;
    private Auteur newBoekAuteur;
    private Uitgeverij newBoekUitgeverij;
    private int newBoekVoorraad;

    /** CONSTRUCTORS */
    public BoekController() {
    }

    /** FUNCTIONS */
    public void createBoek() {
        boekService.createBoek(newBoekTitel, newBoekBeschrijving, newBoekPrijs, newBoekGenre, newBoekAuteur, newBoekUitgeverij, newBoekVoorraad);
        sorteerBoeken();
        _addMessage("Boek toegevoegd!");
        _clearForm();
    }

    public void sorteerBoeken() {
        Collator collator = Collator.getInstance(Locale.US);
        if (!boeken.isEmpty()) {
            Collections.sort(boeken, new Comparator<Boek>() {
                @Override
                public int compare(Boek c1, Boek c2) {
                    //You should ensure that list doesn't contain null values!
                    return collator.compare(c1.getTitel(), c2.getTitel());
                }
            });
        }
    }

    public String toonBoeken(){
        return "./axel.xhtml?faces-redirect=true";
    }
    public String addBoeken(){
        return "./axelAddBoeken.xhtml?faces-redirect=true";
    }

    public String lijstBoeken() {
        List<Boek> alleboeken = boekService.findAllBoeken();
        setBoeken(alleboeken);
        return "/test/lijstBoeken.xhtml?faces-redirect=true";
    }

    public List<Boek> getAllBoeken() {
        return boekService.findAllBoeken();
    }

    public Boek getBoekFromParam() {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        if(params.get("boekId") != null) {
            boek = boekService.findById(Long.parseLong(params.get("boekId")));
        }
        return boek;
    }

    //public String boekDetails() {
    //    Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
    //    if(params.get("boekId") != null) {
    //        setBoek(boekService.findById(Long.parseLong("boekId")));
    //        return "/test/boek.xhtml";
    //    } else {
    //        return "404";
    //    }
    //}

    public void _clearForm() {
        newBoekTitel = null;
        newBoekBeschrijving = null;
        newBoekPrijs = 0.0;
        newBoekGenre = null;
        newBoekAuteur = null;
        newBoekUitgeverij = null;
        newBoekVoorraad = 0;
    }

    private void _addMessage(String summary) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary,  null);
        FacesContext.getCurrentInstance().addMessage(null, message);
    }

    /** GETTERS & SETTERS */
    public String getNewBoekTitel() {
        return newBoekTitel;
    }

    public void setNewBoekTitel(String newBoekTitel) {
        this.newBoekTitel = newBoekTitel;
    }

    public String getNewBoekBeschrijving() {
        return newBoekBeschrijving;
    }

    public void setNewBoekBeschrijving(String newBoekBeschrijving) {
        this.newBoekBeschrijving = newBoekBeschrijving;
    }

    public double getNewBoekPrijs() {
        return newBoekPrijs;
    }

    public void setNewBoekPrijs(double newBoekPrijs) {
        this.newBoekPrijs = newBoekPrijs;
    }

    public Genre getNewBoekGenre() {
        return newBoekGenre;
    }

    public void setNewBoekGenre(Genre newBoekGenre) {
        this.newBoekGenre = newBoekGenre;
    }

    public Auteur getNewBoekAuteur() {
        return newBoekAuteur;
    }

    public void setNewBoekAuteur(Auteur newBoekAuteur) {
        this.newBoekAuteur = newBoekAuteur;
    }

    public Uitgeverij getNewBoekUitgeverij() {
        return newBoekUitgeverij;
    }

    public void setNewBoekUitgeverij(Uitgeverij newBoekUitgeverij) {
        this.newBoekUitgeverij = newBoekUitgeverij;
    }

    public int getNewBoekVoorraad() {
        return newBoekVoorraad;
    }

    public void setNewBoekVoorraad(int newBoekVoorraad) {
        this.newBoekVoorraad = newBoekVoorraad;
    }

    public Boek getBoek() {
        return boek;
    }

    public void setBoek(Boek boek) {
        this.boek = boek;
    }

    public void setBoeken(List<Boek> boeken) {
        this.boeken = boeken;
    }

    /**Deze setter MOET aanwezig zijn, anders kan spring deze service niet injecteren.*/
    public void setBoekService(BoekService boekService) {
        this.boekService = boekService;
    }
    public void setGenreService(GenreService genreService) {
        this.genreService = genreService;
    }
    public void setAuteurService(AuteurService auteurService) {
        this.auteurService = auteurService;
    }
    public void setUitgeverijService(UitgeverijService uitgeverijService) { this.uitgeverijService = uitgeverijService; }

}

src/main/webapp/boeken/boek.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <link rel="stylesheet" type="text/css" href="../css/main.css"/>
</h:head>
<h:body>
    <ui:composition template="../template/template.xhtml">
        <ui:define name="content_titel">
            <h1>#{boekController.boekFromParam.titel}</h1>
        </ui:define>
        <ui:define name="content">
            <div class="container-fluid">
                <div class="col-sm-12 col-md-6">
                    <h5>bescrijving</h5>
                    <div>#{boekController.getBoek().beschrijving}</div>
                </div>
                <div class="col-sm-12 col-md-6">
                    <p>geschreven door: #{boekController.getBoek().auteur}</p>
                    <p>gerne: #{boekController.getBoek().genre.naam}</p>
                    <h5>€ #{boekController.getBoek().prijs}</h5>
                    <h:form>
                        <p>aantal:</p>
                        <p:inputNumber id="aantalBoeken" value="#{winkelmandController.nieuwItem.aantal}" decimalPlaces="0"
                                       minValue="0"/><br/>
                        <p:growl id="growl" life="5000"/>
                        <p:commandButton value="toevoegen aan winkelmand" id="ajax" update="growl" styleClass="btn btn-primary"
                                         actionListener="#{winkelmandController.addItem(boekController.getBoek())}"/>
                        <input type="hidden" name="#{_csrf.parameterName}" value="#{_csrf.token}"/>
                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/boeken/lijstBoeken.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <script name="jquery/jquery.js" src="primefaces"></script>
    <title>Overzicht Boeken</title>
    <link rel="stylesheet" type="text/css" href="../css/main.css"/>
</h:head>
<h:body>
    <ui:composition template="../template/template.xhtml">
        <ui:define name="content_titel">
            <h1>Overzicht Boeken</h1>
        </ui:define>
        <ui:define name="content">
            <h:form>
                <p:dataTable var="boek" value="#{boekController.getAllBoeken()}">
                    <p:column headerText="id">
                        <h:outputText value="#{boek.id}" />
                    </p:column>
                    <p:column headerText="Titel">
                        <p:link outcome="/boeken/boek.xhtml?boekId=#{boek.id}" value="#{boek.titel}"/>
                    </p:column>
                    <p:column headerText="Beschrijving">
                        <h:outputText value="#{boek.beschrijving}" />
                    </p:column>
                    <p:column headerText="Prijs">
                        <h:outputText value="€ #{boek.prijs}" />
                    </p:column>
                    <p:column headerText="Genre">
                        <h:outputText value="#{boek.genre}" />
                    </p:column>
                    <p:column headerText="Auteur">
                        <h:outputText value="#{boek.auteur}" />
                    </p:column>
                    <p:column headerText="Uitgeverij">
                        <h:outputText value="#{boek.uitgeverij}" />
                    </p:column>
                    <p:column headerText="voorraad">
                        <h:outputText value="#{boek.voorraad}" />
                    </p:column>
                </p:dataTable>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>